removing configuration policies Signed-off-by: Ben Carr <9310348+bcarr-rh@users.noreply.github.com>

diff --git a/policies/stable/advanced-cluster-security/manifests/init-bundle/init-bundle-resources.yaml b/policies/stable/advanced-cluster-security/manifests/init-bundle/init-bundle-resources.yaml
--- a/policies/stable/advanced-cluster-security/manifests/init-bundle/init-bundle-resources.yaml
+++ b/policies/stable/advanced-cluster-security/manifests/init-bundle/init-bundle-resources.yaml
@@ -1,187 +1,105 @@
-apiVersion: policy.open-cluster-management.io/v1
-kind: ConfigurationPolicy
-metadata:
-  name: acs-init-bundle-resources
-spec:
-  remediationAction: ${REMEDIATION}
-  severity: high
-  evaluationInterval:
-    compliant: 10m
-    noncompliant: 30s
-  object-templates:
-    - complianceType: musthave
-      objectDefinition:
-        apiVersion: v1
-        kind: Namespace
-        metadata:
-          name: stackrox
-          labels:
-            openshift.io/cluster-monitoring: "true"
-    - complianceType: musthave
-      objectDefinition:
-        apiVersion: v1
-        kind: ServiceAccount
-        metadata:
-          annotations:
-            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
-          name: create-cluster-init
-          namespace: stackrox
-    - complianceType: musthave
-      objectDefinition:
-        apiVersion: rbac.authorization.k8s.io/v1
+object-templates-raw: |
+  - complianceType: musthave
+    objectDefinition:
+      apiVersion: v1
+      kind: Namespace
+      metadata:
+        name: stackrox
+        labels:
+          openshift.io/cluster-monitoring: 'true'
+  - complianceType: musthave
+    objectDefinition:
+      apiVersion: v1
+      kind: ServiceAccount
+      metadata:
+        annotations:
+          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
+        name: create-cluster-init
+        namespace: stackrox
+  - complianceType: musthave
+    objectDefinition:
+      apiVersion: rbac.authorization.k8s.io/v1
+      kind: Role
+      metadata:
+        name: create-cluster-init
+        namespace: stackrox
+      rules:
+      - apiGroups:
+        - ''
+        resources:
+        - secrets
+        verbs:
+        - get
+        - list
+        - create
+        - patch
+        - update
+      - apiGroups:
+        - platform.stackrox.io
+        resources:
+        - securedclusters
+        verbs:
+        - get
+        - list
+        - patch
+        - update
+      - apiGroups:
+        - route.openshift.io
+        resources:
+        - routes
+        verbs:
+        - get
+        - list
+  - complianceType: musthave
+    objectDefinition:
+      apiVersion: rbac.authorization.k8s.io/v1
+      kind: RoleBinding
+      metadata:
+        annotations:
+          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
+        name: create-cluster-init
+        namespace: stackrox
+      roleRef:
+        apiGroup: rbac.authorization.k8s.io
         kind: Role
-        metadata:
-          name: create-cluster-init
-          namespace: stackrox
-        rules:
-        - apiGroups:
-          - ""
-          resources:
-          - secrets
-          verbs:
-          - get
-          - list
-          - create
-          - patch
-          - update
-        - apiGroups:
-          - platform.stackrox.io
-          resources:
-          - securedclusters
-          verbs:
-          - get
-          - list
-          - patch
-          - update
-        - apiGroups:
-          - route.openshift.io
-          resources:
-          - routes
-          verbs:
-          - get
-          - list
-    - complianceType: musthave
-      objectDefinition:
-        apiVersion: rbac.authorization.k8s.io/v1
-        kind: RoleBinding
-        metadata:
-          annotations:
-            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
-          name: create-cluster-init
-          namespace: stackrox
-        roleRef:
-          apiGroup: rbac.authorization.k8s.io
-          kind: Role
-          name: create-cluster-init
-        subjects:
-        - kind: ServiceAccount
-          name: create-cluster-init
-          namespace: stackrox
-    - complianceType: musthave
-      objectDefinition:
-        apiVersion: batch/v1
-        kind: Job
-        metadata:
-          name: create-cluster-init-bundle-v2
-          namespace: stackrox
-          labels:
-            init-bundle: central
-        spec:
-          template:
-            metadata:
-              annotations:
-                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
-              labels:
-                init-bundle: central
-            spec:
-              containers:
-              - command:
-                - /bin/bash
-                - -c
-                - |
-                  #!/usr/bin/env bash
-                  if kubectl get secret/sensor-tls &> /dev/null; then
-                    echo "cluster-init bundle has already been configured, doing nothing"
-                    exit 0
-                  else
-
-                    # Wait for central to be ready
-                    attempt_counter=0
-                    max_attempts=20
-                    echo "Waiting for central to be available..."
-                    until $(curl -k --output /dev/null --silent --head --fail https://central); do
-                        if [ ${attempt_counter} -eq ${max_attempts} ];then
-                          echo "Max attempts reached"
-                          exit 1
-                        fi
-
-                        printf '.'
-                        attempt_counter=$(($attempt_counter+1))
-                        echo "Made attempt $attempt_counter, waiting..."
-                        sleep 5
-                    done
-
-                    # attempt to create init-bundle
-                    # on failure attempt to delete the bundle
-                    attempt_counter=0
-                    max_attempts=5
-                    echo "Configuring cluster-init bundle"
-
-                    # set the bundle name to include todays date
-                    bundle_name=local-cluster-$(date '+%Y%m%d')
-                    export DATA={\"name\":\"$bundle_name\"}
-                    until (curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA --fail https://central/v1/cluster-init/init-bundles); do
-                        if [ ${attempt_counter} -eq ${max_attempts} ];then
-                          echo "Max attempts to create bundle reached"
-                          exit 1
-                        fi
-
-                        echo "Check to see if there is an existing bundle that can be revoked"
-                        curl -o /tmp/find_bundle.json  -k -X GET -u "admin:$PASSWORD" -H "Content-Type: application/json" https://central/v1/cluster-init/init-bundles
-                        bundle_id=$(cat /tmp/find_bundle.json | python -c "import sys, json; result = [x for x in json.load(sys.stdin)[\"items\"] if x[\"name\"]==\"$bundle_name\"]; print(result[0][\"id\"])")
-
-                        echo "-------------------------"
-                        echo "bundle name is $bundle_name bundle id $bundle_id"
-                        echo "-------------------------"
-
-                        if [ "${bundle_id}" != "" ];then
-                        echo "executing revoke command"
-                          export REVOKE="{\"ids\":[\"$bundle_id\"],\"confirmImpactedClustersIds\":[]}"
-                          curl -k -X PATCH -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $REVOKE https://central/v1/cluster-init/init-bundles/revoke
-                        fi
-
-                        printf '.'
-                        attempt_counter=$(($attempt_counter+1))
-                        echo "Made create bundle attempt $attempt_counter, waiting..."
-                        sleep 5
-                    done
-
-                    echo "Bundle received"
-
-                    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-                        BASE='base64 -w 0'
-                    elif [[ "$OSTYPE" == "darwin"* ]]; then
-                        BASE='base64'
-                    fi
-
-                    echo "Applying bundle"
-                    # No jq in container, python to the rescue
-                    cat /tmp/bundle.json | python3 -c "import sys, json; print(json.load(sys.stdin)['kubectlBundle'])" | ${BASE} -d | oc apply -f -
-                    ACS_HOST="$(oc get route central -o custom-columns=HOST:.spec.host --no-headers):443"
-                    oc patch secret sensor-tls --type='json' -p="[{\"op\" : \"add\", \"path\" : \"/data/acs-host\", \"value\" : \"$(echo $ACS_HOST | ${BASE})\"}]"
-                    echo "ACS Cluster init bundle generated and applied"
-                  fi
-                env:
-                - name: PASSWORD
-                  valueFrom:
-                    secretKeyRef:
-                      key: password
-                      name: central-htpasswd
-                image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
-                imagePullPolicy: Always
-                name: create-cluster-init-bundle
-              dnsPolicy: ClusterFirst
-              restartPolicy: Never
-              serviceAccount: create-cluster-init
-              serviceAccountName: create-cluster-init
-              terminationGracePeriodSeconds: 30
+        name: create-cluster-init
+      subjects:
+      - kind: ServiceAccount
+        name: create-cluster-init
+        namespace: stackrox
+  - complianceType: musthave
+    objectDefinition:
+      apiVersion: batch/v1
+      kind: Job
+      metadata:
+        name: create-cluster-init-bundle-v2
+        namespace: stackrox
+        labels:
+          init-bundle: central
+      spec:
+        template:
+          metadata:
+            annotations:
+              argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
+            labels:
+              init-bundle: central
+          spec:
+            containers:
+            - command:
+              - /bin/bash
+              - -c
+              - "#!/usr/bin/env bash\nif kubectl get secret/sensor-tls &> /dev/null; then\n  echo \"cluster-init bundle has already been configured, doing nothing\"\n  exit 0\nelse\n\n  # Wait for central to be ready\n  attempt_counter=0\n  max_attempts=20\n  echo \"Waiting for central to be available...\"\n  until $(curl -k --output /dev/null --silent --head --fail https://central); do\n      if [ ${attempt_counter} -eq ${max_attempts} ];then\n        echo \"Max attempts reached\"\n        exit 1\n      fi\n\n      printf '.'\n      attempt_counter=$(($attempt_counter+1))\n      echo \"Made attempt $attempt_counter, waiting...\"\n      sleep 5\n  done\n\n  # attempt to create init-bundle\n  # on failure attempt to delete the bundle\n  attempt_counter=0\n  max_attempts=5\n  echo \"Configuring cluster-init bundle\"\n\n  # set the bundle name to include todays date\n  bundle_name=local-cluster-$(date '+%Y%m%d')\n  export DATA={\\\"name\\\":\\\"$bundle_name\\\"}\n  until (curl -k -o /tmp/bundle.json -X POST -u \"admin:$PASSWORD\" -H \"Content-Type: application/json\" --data $DATA --fail https://central/v1/cluster-init/init-bundles); do\n      if [ ${attempt_counter} -eq ${max_attempts} ];then\n        echo \"Max attempts to create bundle reached\"\n        exit 1\n      fi\n\n      echo \"Check to see if there is an existing bundle that can be revoked\"\n      curl -o /tmp/find_bundle.json  -k -X GET -u \"admin:$PASSWORD\" -H \"Content-Type: application/json\" https://central/v1/cluster-init/init-bundles\n      bundle_id=$(cat /tmp/find_bundle.json | python -c \"import sys, json; result = [x for x in json.load(sys.stdin)[\\\"items\\\"] if x[\\\"name\\\"]==\\\"$bundle_name\\\"]; print(result[0][\\\"id\\\"])\")\n\n      echo \"-------------------------\"\n      echo \"bundle name is $bundle_name bundle id $bundle_id\"\n      echo \"-------------------------\"\n\n      if [ \"${bundle_id}\" != \"\" ];then\n      echo \"executing revoke command\"\n        export REVOKE=\"{\\\"ids\\\":[\\\"$bundle_id\\\"],\\\"confirmImpactedClustersIds\\\":[]}\"\n        curl -k -X PATCH -u \"admin:$PASSWORD\" -H \"Content-Type: application/json\" --data $REVOKE https://central/v1/cluster-init/init-bundles/revoke\n      fi\n\n      printf '.'\n      attempt_counter=$(($attempt_counter+1))\n      echo \"Made create bundle attempt $attempt_counter, waiting...\"\n      sleep 5\n  done\n\n  echo \"Bundle received\"\n\n  if [[ \"$OSTYPE\" == \"linux-gnu\"* ]]; then\n      BASE='base64 -w 0'\n  elif [[ \"$OSTYPE\" == \"darwin\"* ]]; then\n      BASE='base64'\n  fi\n\n  echo \"Applying bundle\"\n  # No jq in container, python to the rescue\n  cat /tmp/bundle.json | python3 -c \"import sys, json; print(json.load(sys.stdin)['kubectlBundle'])\" | ${BASE} -d | oc apply -f -\n  ACS_HOST=\"$(oc get route central -o custom-columns=HOST:.spec.host --no-headers):443\"\n  oc patch secret sensor-tls --type='json' -p=\"[{\\\"op\\\" : \\\"add\\\", \\\"path\\\" : \\\"/data/acs-host\\\", \\\"value\\\" : \\\"$(echo $ACS_HOST | ${BASE})\\\"}]\"\n  echo \"ACS Cluster init bundle generated and applied\"\nfi\n"
+              env:
+              - name: PASSWORD
+                valueFrom:
+                  secretKeyRef:
+                    key: password
+                    name: central-htpasswd
+              image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
+              imagePullPolicy: Always
+              name: create-cluster-init-bundle
+            dnsPolicy: ClusterFirst
+            restartPolicy: Never
+            serviceAccount: create-cluster-init
+            serviceAccountName: create-cluster-init
+            terminationGracePeriodSeconds: 30
